### ISSUE TITLE
node-fetch version 3+ requires a dynamic import

### ISSUE THREAD

**Issue by piqueen314** [netlify/explorers-up-and-running-with-serverless-functions#7]
pokedex.js needs to import node-fetch dynamically
const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));

**Comment by piqueen314** [comment]
people following the tutorial will probably do 
npm install --save-dev node-fetch
and get a version of node-fetch greater than 3

**Comment by bencodezen** [comment]
Everything should be good to go now! Thank you for writing this issue!
